"""异常模块

提供统一的异常处理机制，包括：
- 分层错误码（模块.编号）
- i18n错误消息（预留）
- 统一的异常基类
- 全局异常处理器

使用示例:
    >>> from graphedu.common.exceptions import (
    ...     RegisterUsernameExistsException,
    ...     ErrorCode
    ... )
    >>>
    >>> # 抛出异常
    >>> raise RegisterUsernameExistsException(username="zhangsan")
    >>>
    >>> # 响应格式:
    >>> # {
    >>> #   "code": 409,
    >>> #   "errorCode": "AUTH.12201",
    >>> #   "msg": "用户注册失败，用户名zhangsan已被注册",
    >>> #   "data": {},
    >>> #   "time": "2025-01-15T12:00:00Z"
    >>> # }
"""

# 错误码
# 全局异常处理器
# 配置相关异常
from graphedu.common.exceptions.common.config import (
    ConfigurationException,
    ConfigurationInstantiationException,
    ConfigurationParseException,
    ConfigurationReadException,
    ConfigurationWriteException,
)

# 资源层相关异常
from graphedu.common.exceptions.common.resource import (
    # 异步执行器相关
    AsyncExecutorException,
    AsyncExecutorNotInitializedException,
    AsyncExecutorPoolExhaustedException,
    AsyncExecutorShutdownException,
    AsyncExecutorSubmitException,
    AsyncExecutorTimeoutException,
    AsyncExecutorValidationException,
    CacheClientException,
    CacheConfigValidationException,
    CacheConnectionException,
    CacheDisconnectedException,
    # 缓存相关
    CacheException,
    CacheOperationException,
    CachePoolException,
    CacheTimeoutException,
    DatabaseConfigValidationException,
    DatabaseConnectionException,
    DatabaseDisconnectedException,
    DatabaseEngineException,
    # 数据库相关
    DatabaseException,
    DatabaseExecuteException,
    DatabasePoolExhaustedException,
    DatabaseQueryException,
    DatabaseSessionException,
    DatabaseTransactionException,
    FileDeleteException,
    FileDownloadException,
    FileNotFoundException,
    FilePresignedUrlException,
    FileUploadException,
    # 图数据库相关
    GraphDatabaseConfigValidationException,
    GraphDatabaseConnectionException,
    GraphDatabaseDisconnectedException,
    GraphDatabaseDriverException,
    GraphDatabaseException,
    GraphDatabaseExecuteException,
    GraphDatabaseQueryException,
    HTTPClientException,
    HTTPConnectionException,
    # HTTP 客户端相关
    HTTPException,
    HTTPRequestException,
    HTTPTimeoutException,
    # 资源异常基类
    ResourceException,
    # 资源初始化/关闭相关
    ResourceInitializationException,
    ResourceNotInitializedException,
    ResourceShutdownException,
    # 存储相关
    StorageClientException,
    StorageConfigValidationException,
    StorageConnectionException,
    StorageException,
    StorageOperationException,
)

# 工具类异常
from graphedu.common.exceptions.common.utils import (
    ConcurrentException,
    FileException,
    FileParseException,
    FileReadException,
    FileWriteException,
    ImportException,
    JSONException,
    JSONParseException,
    JSONValidationException,
    LLMConnectionException,
    LLMException,
    LLMRateLimitException,
    LLMResponseException,
    LLMTokenLimitException,
    LockException,
    RateLimitException,
    TypeConversionException,
    TypeException,
    UtilsException,
    UtilsFileNotFoundException,
    UtilsTimeoutException,
    ValidationException,
    ValueException,
    format_exception,
    get_exception_chain,
)
from graphedu.common.exceptions.handler import handle_exception

# 基础异常类
from graphedu.common.exceptions.services.base import ServiceException, ServiceWarning
from graphedu.common.exceptions.services.codes import ErrorCode

# 认证授权相关异常
from graphedu.common.exceptions.services.system.auth import (
    LoginAccountDisabledException,
    LoginAccountExpiredException,
    LoginAccountLockedException,
    LoginAccountNotActivatedException,
    LoginAccountPendingReviewException,
    LoginAccountRejectedException,
    LoginCaptchaErrorException,
    LoginCaptchaExpiredException,
    LoginCaptchaRequiredException,
    LoginCredentialsExpiredException,
    # 登录
    LoginException,
    LoginFailedException,
    LoginIpErrorException,
    LoginPasswordErrorException,
    LoginSessionExpiredException,
    LoginSessionInvalidException,
    LoginTimeoutException,
    LoginTooManyAttemptsException,
    LoginUnsupportedException,
    LoginUsernameLockedException,
    LoginUserNotFoundException,
    NoFunctionPermissionException,
    NoInterfacePermissionException,
    # 密码
    PasswordException,
    PasswordExpiredException,
    PasswordIncorrectException,
    PasswordResetRequiredException,
    PasswordSameAsOldException,
    PasswordTooWeakException,
    # 权限
    PermissionDeniedException,
    RegisterEmailExistsException,
    # 注册
    RegisterException,
    RegisterFunctionDisabledException,
    RegisterIllegalDoublePasswordException,
    RegisterIllegalEmailException,
    RegisterIllegalPasswordException,
    RegisterIllegalPhoneException,
    RegisterIllegalUsernameException,
    RegisterPhonenumberExistsException,
    RegisterUsernameExistsException,
    # Token
    TokenException,
    TokenExpiredException,
    TokenInvalidException,
    TokenMalformedException,
    TokenMissingException,
    TokenRefreshFailedException,
    TokenSignatureInvalidException,
)

# 部门相关异常
from graphedu.common.exceptions.services.system.dept import (
    DeptAlreadyExistsException,
    DeptDeleteFailedException,
    DeptException,
    DeptHasActiveChildrenException,
    DeptHasChildrenException,
    DeptHasUsersException,
    DeptIdListEmptyException,
    DeptKeyAlreadyExistsException,
    DeptNameAlreadyExistsException,
    DeptNoPermissionException,
    DeptNotFoundException,
    DeptParentCycleException,
    DeptParentDisabledException,
    DeptParentItselfException,
    DeptParentNotFoundException,
)

# 数据字典相关异常
from graphedu.common.exceptions.services.system.dict import (
    DictDataAlreadyExistsException,
    DictDataCreateFailedException,
    DictDataDeleteFailedException,
    DictDataIdListEmptyException,
    DictDataNotFoundException,
    DictDataUpdateFailedException,
    DictException,
    DictTypeAlreadyExistsException,
    DictTypeCreateFailedException,
    DictTypeDeleteFailedException,
    DictTypeHasDataException,
    DictTypeIdListEmptyException,
    DictTypeNotFoundException,
    DictTypeUpdateFailedException,
)

# 功能相关异常
from graphedu.common.exceptions.services.system.function import (
    FunctionAlreadyExistsException,
    FunctionAssignedToRoleException,
    FunctionException,
    FunctionExternalLinkInvalidException,
    FunctionHasChildrenException,
    FunctionNameAlreadyExistsException,
    FunctionNotFoundException,
    FunctionParentItselfException,
)

# 定时任务相关异常
from graphedu.common.exceptions.services.system.job import (
    JobChangeStatusFailedException,
    JobConfigInvalidException,
    JobCreateFailedException,
    JobCronInvalidException,
    JobDeleteFailedException,
    JobException,
    JobExecuteFailedException,
    JobIdListEmptyException,
    JobLogClearFailedException,
    JobLogDeleteFailedException,
    JobLogIdListEmptyException,
    JobLogNotFoundException,
    JobNameAlreadyExistsException,
    JobNoPermissionException,
    JobNotFoundException,
    JobTargetInvalidException,
    JobUpdateFailedException,
)

# 角色相关异常
from graphedu.common.exceptions.services.system.role import (
    RoleAlreadyExistsException,
    RoleAuthorizeUsersFailedException,
    RoleChangeAdminStatusForbiddenException,
    RoleDeleteAdminForbiddenException,
    RoleDeleteFailedException,
    RoleException,
    RoleHasUsersException,
    RoleIdListEmptyException,
    RoleKeyAlreadyExistsException,
    RoleModifyAdminForbiddenException,
    RoleNameAlreadyExistsException,
    RoleNoPermissionException,
    RoleNotFoundException,
    RoleRevokeUsersBatchFailedException,
    RoleRevokeUsersFailedException,
    RoleUpdateDataScopeFailedException,
)

# 文件上传下载相关异常
from graphedu.common.exceptions.services.system.upload import (
    DownloadFailedException,
    DownloadFileNotFoundException,
    DownloadNoPermissionException,
    DownloadNotAllowedException,
    UploadException,
    UploadFailedException,
    UploadFilenameEmptyException,
    UploadFileNotFoundException,
    UploadFileTooLargeException,
    UploadFileTypeNotAllowed,
    UploadS3ClientNotInitialized,
    UploadS3ConfigNotInitialized,
)

# 用户相关异常
from graphedu.common.exceptions.services.system.user import (
    UserAlreadyExistsException,
    UserAvatarOwnershipException,
    UserCannotChangeOwnPasswordException,
    UserDeactivatedException,
    UserDeleteAdminForbiddenException,
    UserDeleteFailedException,
    UserDisabledException,
    UserEmailAlreadyExistsException,
    UserException,
    UserIdListEmptyException,
    UserIdNotFoundException,
    UserNoPermissionException,
    UserNotFoundException,
    UserOldPasswordIncorrectException,
    UserOnlyAdminException,
    UserPasswordUnchangeException,
    UserPhoneAlreadyExistsException,
    UserResetPasswordFailedException,
    UserUpdateFailedException,
    UserUpdateRoleFailedException,
)

__all__ = [
    "AsyncExecutorException",
    "AsyncExecutorNotInitializedException",
    "AsyncExecutorPoolExhaustedException",
    "AsyncExecutorShutdownException",
    "AsyncExecutorSubmitException",
    "AsyncExecutorTimeoutException",
    "AsyncExecutorValidationException",
    "CacheClientException",
    "CacheConfigValidationException",
    "CacheConnectionException",
    "CacheDisconnectedException",
    "CacheException",
    "CacheOperationException",
    "CachePoolException",
    "CacheTimeoutException",
    "ConcurrentException",
    "ConfigurationException",
    "ConfigurationInstantiationException",
    "ConfigurationParseException",
    "ConfigurationReadException",
    "ConfigurationWriteException",
    "DatabaseConfigValidationException",
    "DatabaseConnectionException",
    "DatabaseDisconnectedException",
    "DatabaseEngineException",
    "DatabaseException",
    "DatabaseExecuteException",
    "DatabasePoolExhaustedException",
    "DatabaseQueryException",
    "DatabaseSessionException",
    "DatabaseTransactionException",
    "DeptAlreadyExistsException",
    "DeptDeleteFailedException",
    "DeptException",
    "DeptHasActiveChildrenException",
    "DeptHasChildrenException",
    "DeptHasUsersException",
    "DeptIdListEmptyException",
    "DeptKeyAlreadyExistsException",
    "DeptNameAlreadyExistsException",
    "DeptNoPermissionException",
    "DeptNotFoundException",
    "DeptParentCycleException",
    "DeptParentDisabledException",
    "DeptParentItselfException",
    "DeptParentNotFoundException",
    "DictDataAlreadyExistsException",
    "DictDataCreateFailedException",
    "DictDataDeleteFailedException",
    "DictDataIdListEmptyException",
    "DictDataNotFoundException",
    "DictDataUpdateFailedException",
    "DictException",
    "DictTypeAlreadyExistsException",
    "DictTypeCreateFailedException",
    "DictTypeDeleteFailedException",
    "DictTypeHasDataException",
    "DictTypeIdListEmptyException",
    "DictTypeNotFoundException",
    "DictTypeUpdateFailedException",
    "DownloadFailedException",
    "DownloadFileNotFoundException",
    "DownloadNoPermissionException",
    "DownloadNotAllowedException",
    "ErrorCode",
    "FileDeleteException",
    "FileDownloadException",
    "FileException",
    "FileNotFoundException",
    "FileParseException",
    "FilePresignedUrlException",
    "FileReadException",
    "FileUploadException",
    "FileWriteException",
    "FunctionAlreadyExistsException",
    "FunctionAssignedToRoleException",
    "FunctionException",
    "FunctionExternalLinkInvalidException",
    "FunctionHasChildrenException",
    "FunctionNameAlreadyExistsException",
    "FunctionNotFoundException",
    "FunctionParentItselfException",
    "GraphDatabaseConfigValidationException",
    "GraphDatabaseConnectionException",
    "GraphDatabaseDisconnectedException",
    "GraphDatabaseDriverException",
    "GraphDatabaseException",
    "GraphDatabaseExecuteException",
    "GraphDatabaseQueryException",
    "HTTPClientException",
    "HTTPConnectionException",
    "HTTPException",
    "HTTPRequestException",
    "HTTPTimeoutException",
    "ImportException",
    "JSONException",
    "JSONParseException",
    "JSONValidationException",
    "JobChangeStatusFailedException",
    "JobConfigInvalidException",
    "JobCreateFailedException",
    "JobCronInvalidException",
    "JobDeleteFailedException",
    "JobException",
    "JobExecuteFailedException",
    "JobIdListEmptyException",
    "JobLogClearFailedException",
    "JobLogDeleteFailedException",
    "JobLogIdListEmptyException",
    "JobLogNotFoundException",
    "JobNameAlreadyExistsException",
    "JobNoPermissionException",
    "JobNotFoundException",
    "JobTargetInvalidException",
    "JobUpdateFailedException",
    "LLMConnectionException",
    "LLMException",
    "LLMRateLimitException",
    "LLMResponseException",
    "LLMTokenLimitException",
    "LockException",
    "LoginAccountDisabledException",
    "LoginAccountExpiredException",
    "LoginAccountLockedException",
    "LoginAccountNotActivatedException",
    "LoginAccountPendingReviewException",
    "LoginAccountRejectedException",
    "LoginCaptchaErrorException",
    "LoginCaptchaExpiredException",
    "LoginCaptchaRequiredException",
    "LoginCredentialsExpiredException",
    "LoginException",
    "LoginFailedException",
    "LoginIpErrorException",
    "LoginPasswordErrorException",
    "LoginSessionExpiredException",
    "LoginSessionInvalidException",
    "LoginTimeoutException",
    "LoginTooManyAttemptsException",
    "LoginUnsupportedException",
    "LoginUserNotFoundException",
    "LoginUsernameLockedException",
    "NoFunctionPermissionException",
    "NoInterfacePermissionException",
    "PasswordException",
    "PasswordExpiredException",
    "PasswordIncorrectException",
    "PasswordResetRequiredException",
    "PasswordSameAsOldException",
    "PasswordTooWeakException",
    "PermissionDeniedException",
    "RateLimitException",
    "RegisterEmailExistsException",
    "RegisterException",
    "RegisterFunctionDisabledException",
    "RegisterIllegalDoublePasswordException",
    "RegisterIllegalEmailException",
    "RegisterIllegalPasswordException",
    "RegisterIllegalPhoneException",
    "RegisterIllegalUsernameException",
    "RegisterPhonenumberExistsException",
    "RegisterUsernameExistsException",
    "ResourceException",
    "ResourceInitializationException",
    "ResourceNotInitializedException",
    "ResourceShutdownException",
    "RoleAlreadyExistsException",
    "RoleAuthorizeUsersFailedException",
    "RoleChangeAdminStatusForbiddenException",
    "RoleDeleteAdminForbiddenException",
    "RoleDeleteFailedException",
    "RoleException",
    "RoleHasUsersException",
    "RoleIdListEmptyException",
    "RoleKeyAlreadyExistsException",
    "RoleModifyAdminForbiddenException",
    "RoleNameAlreadyExistsException",
    "RoleNoPermissionException",
    "RoleNotFoundException",
    "RoleRevokeUsersBatchFailedException",
    "RoleRevokeUsersFailedException",
    "RoleUpdateDataScopeFailedException",
    "ServiceException",
    "ServiceWarning",
    "StorageClientException",
    "StorageConfigValidationException",
    "StorageConnectionException",
    "StorageException",
    "StorageOperationException",
    "TokenException",
    "TokenExpiredException",
    "TokenInvalidException",
    "TokenMalformedException",
    "TokenMissingException",
    "TokenRefreshFailedException",
    "TokenSignatureInvalidException",
    "TypeConversionException",
    "TypeException",
    "UploadException",
    "UploadFailedException",
    "UploadFileNotFoundException",
    "UploadFileTooLargeException",
    "UploadFileTypeNotAllowed",
    "UploadFilenameEmptyException",
    "UploadS3ClientNotInitialized",
    "UploadS3ConfigNotInitialized",
    "UserAlreadyExistsException",
    "UserAvatarOwnershipException",
    "UserCannotChangeOwnPasswordException",
    "UserDeactivatedException",
    "UserDeleteAdminForbiddenException",
    "UserDeleteFailedException",
    "UserDisabledException",
    "UserEmailAlreadyExistsException",
    "UserException",
    "UserIdListEmptyException",
    "UserIdNotFoundException",
    "UserNoPermissionException",
    "UserNotFoundException",
    "UserOldPasswordIncorrectException",
    "UserOnlyAdminException",
    "UserPasswordUnchangeException",
    "UserPhoneAlreadyExistsException",
    "UserResetPasswordFailedException",
    "UserUpdateFailedException",
    "UserUpdateRoleFailedException",
    "UtilsException",
    "UtilsFileNotFoundException",
    "UtilsTimeoutException",
    "ValidationException",
    "ValueException",
    "format_exception",
    "get_exception_chain",
    "handle_exception",
]
