-- ============================================================================
-- 1. 定时任务表 (sys_job)
-- ============================================================================
CREATE TABLE IF NOT EXISTS sys_job (
    job_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_name VARCHAR(64) NOT NULL,
    job_group VARCHAR(64) NOT NULL DEFAULT 'DEFAULT',
    job_executor VARCHAR(32) NOT NULL DEFAULT 'python',
    invoke_target VARCHAR(512) NOT NULL,
    job_args TEXT,
    job_kwargs TEXT,
    cron_expression VARCHAR(128) NOT NULL,
    misfire_policy CHAR(1) NOT NULL DEFAULT '1',
    concurrent CHAR(1) NOT NULL DEFAULT '0',
    status CHAR(1) NOT NULL DEFAULT '0',
    webhook_enabled CHAR(1) NOT NULL DEFAULT '0',
    webhook_url VARCHAR(512),
    webhook_secret VARCHAR(128),
    create_by BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(500)
);

-- 添加注释
COMMENT ON TABLE sys_job IS '定时任务表';
COMMENT ON COLUMN sys_job.job_id IS '任务ID';
COMMENT ON COLUMN sys_job.job_name IS '任务名称';
COMMENT ON COLUMN sys_job.job_group IS '任务分组（DEFAULT=默认, SYSTEM=系统）';
COMMENT ON COLUMN sys_job.job_executor IS '执行器类型（python=Python函数, webhook=Webhook调用）';
COMMENT ON COLUMN sys_job.invoke_target IS '调用目标字符串（python: module.function 或 webhook: webhook_entry）';
COMMENT ON COLUMN sys_job.job_args IS '位置参数（JSON格式）';
COMMENT ON COLUMN sys_job.job_kwargs IS '关键字参数（JSON格式）';
COMMENT ON COLUMN sys_job.cron_expression IS 'Cron执行表达式';
COMMENT ON COLUMN sys_job.misfire_policy IS '执行策略（1=立即执行, 2=执行一次, 3=放弃执行）';
COMMENT ON COLUMN sys_job.concurrent IS '是否并发（0=禁止, 1=允许）';
COMMENT ON COLUMN sys_job.status IS '状态（0=正常, 1=暂停）';
COMMENT ON COLUMN sys_job.webhook_enabled IS '是否启用Webhook（0=否, 1=是）';
COMMENT ON COLUMN sys_job.webhook_url IS 'Webhook URL';
COMMENT ON COLUMN sys_job.webhook_secret IS 'Webhook密钥';
COMMENT ON COLUMN sys_job.create_by IS '创建者';
COMMENT ON COLUMN sys_job.create_time IS '创建时间';
COMMENT ON COLUMN sys_job.update_by IS '更新者';
COMMENT ON COLUMN sys_job.update_time IS '更新时间';
COMMENT ON COLUMN sys_job.remark IS '备注';

-- 创建索引
CREATE INDEX idx_sys_job_job_group ON sys_job(job_group);
CREATE INDEX idx_sys_job_job_executor ON sys_job(job_executor);
CREATE INDEX idx_sys_job_status ON sys_job(status);

-- ============================================================================
-- 2. 定时任务执行日志表 (sys_job_log)
-- ============================================================================
CREATE TABLE IF NOT EXISTS sys_job_log (
    job_log_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_id BIGINT NOT NULL,
    job_name VARCHAR(64) NOT NULL,
    job_group VARCHAR(64) NOT NULL,
    invoke_target VARCHAR(512) NOT NULL,
    job_message TEXT,
    status CHAR(1) NOT NULL DEFAULT '0',
    exception_info TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 添加注释
COMMENT ON TABLE sys_job_log IS '定时任务执行日志表';
COMMENT ON COLUMN sys_job_log.job_log_id IS '日志ID';
COMMENT ON COLUMN sys_job_log.job_id IS '任务ID';
COMMENT ON COLUMN sys_job_log.job_name IS '任务名称';
COMMENT ON COLUMN sys_job_log.job_group IS '任务分组';
COMMENT ON COLUMN sys_job_log.invoke_target IS '调用目标字符串';
COMMENT ON COLUMN sys_job_log.job_message IS '执行信息';
COMMENT ON COLUMN sys_job_log.status IS '执行状态（0=成功, 1=失败）';
COMMENT ON COLUMN sys_job_log.exception_info IS '异常信息';
COMMENT ON COLUMN sys_job_log.create_time IS '创建时间';

-- 创建索引
CREATE INDEX idx_sys_job_log_job_id ON sys_job_log(job_id);
CREATE INDEX idx_sys_job_log_status ON sys_job_log(status);
CREATE INDEX idx_sys_job_log_create_time ON sys_job_log(create_time);