[project]
name = "graphrag-pgvector"
version = "0.0.1"
description = "GraphRAG plugin for pgvector"
requires-python = ">=3.11,<3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "graphrag-common==3.0.8",
    "numpy~=2.1",
    "pgvector~=0.4",
    "psycopg[binary]>=3.1",
    "psycopg-pool>=3.1",
    "pyarrow~=22.0",
    "pydantic~=2.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
